name: Example workflow for using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for Python vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true 
      - name: Run Snyk to check for NodeJS vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true 
      - name: Run Snyk to check for Java vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        with:
          command: monitor
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
